# Конфигурация для ГОСТ Анализатора

# Настройки LLM
llm:
  provider: "openai"  # openai, anthropic, local
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 4096

# Настройки RAG
rag:
  chunk_size: 1000
  chunk_overlap: 200
  embedding_model: "text-embedding-ada-002"
  vector_store: "chromadb"
  top_k: 5

# Пути к данным
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  output: "data/output"

# Целевые объекты для извлечения
targets:
  - "C235"
  - "C245"
  - "C255"
  - "C345"
  - "C390"
  - "C440"

# Настройки логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
